### ISSUE TITLE
Undefined method `import'

### ISSUE THREAD

**Issue by gshopovski** [SnezanaDichevska/bigbrotha#1]
I'm getting an error when updating one of the columns which is configured in the initializer:

NoMethodError: undefined method `import' for #Class:0x007fa37e9ad598

The initializer is setup like this:

```
BigBrotha.configure do |config|
  config.add(User, :self, [:display_name], :before, :save)
end
```

Taboo word is successfully added, and the error occurs when updating the model:

```
BigBrotha.add_taboo!("princess")
user.update(display_name: "I'm princessita")
```

**Comment by SnezanaDichevska** [comment]
added dependencies , sorry :D
